# Generated by Django 3.2.6 on 2021-10-07 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labguide', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test_information',
            old_name='stability',
            new_name='room_temp_stability',
        ),
        migrations.AddField(
            model_name='test_information',
            name='frozen_stability',
            field=models.CharField(default='X', max_length=200),
        ),
        migrations.AddField(
            model_name='test_information',
            name='refrigerated_stability',
            field=models.CharField(default='X', max_length=200),
        ),
        migrations.AddField(
            model_name='test_information',
            name='test_code',
            field=models.CharField(default='X', max_length=25),
        ),
    ]
