# Generated by Django 3.2.6 on 2021-10-18 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labguide', '0002_auto_20211007_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test_information',
            old_name='room_temp_stability',
            new_name='stability',
        ),
        migrations.RemoveField(
            model_name='test_information',
            name='frozen_stability',
        ),
        migrations.RemoveField(
            model_name='test_information',
            name='refrigerated_stability',
        ),
        migrations.RemoveField(
            model_name='test_information',
            name='test_code',
        ),
    ]
