# Generated by Django 3.2.6 on 2021-11-01 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labguide', '0003_auto_20211018_1858'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test_Information',
        ),
    ]
