# Generated by Django 3.2.6 on 2021-09-01 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testinformation', '0002_test_information_test_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test_information',
            old_name='stability',
            new_name='room_temp_stability',
        ),
        migrations.AddField(
            model_name='test_information',
            name='frozen_stability',
            field=models.CharField(default='X', max_length=200),
        ),
        migrations.AddField(
            model_name='test_information',
            name='refrigerated_stability',
            field=models.CharField(default='X', max_length=200),
        ),
    ]
