# Generated by Django 3.2.6 on 2021-10-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testinformation', '0003_auto_20210901_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_information',
            name='appropriate_tubetype_three',
            field=models.CharField(default='X', max_length=200),
        ),
        migrations.AddField(
            model_name='test_information',
            name='appropriate_tubetype_two',
            field=models.CharField(default='X', max_length=200),
        ),
        migrations.AlterField(
            model_name='test_information',
            name='appropriate_tubetype',
            field=models.CharField(default='X', max_length=200),
        ),
        migrations.AlterField(
            model_name='test_information',
            name='room_temp_stability',
            field=models.CharField(default='X', max_length=200),
        ),
    ]
