# Generated by Django 3.2.6 on 2021-10-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testinformation', '0004_auto_20211018_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_information',
            name='appropriate_tubetype_three',
            field=models.CharField(blank=True, default='X', max_length=200),
        ),
        migrations.AlterField(
            model_name='test_information',
            name='appropriate_tubetype_two',
            field=models.CharField(blank=True, default='X', max_length=200),
        ),
    ]
