# Generated by Django 3.2.6 on 2021-10-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testinformation', '0005_auto_20211018_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test_information',
            old_name='test_code',
            new_name='amr',
        ),
        migrations.AddField(
            model_name='test_information',
            name='avaliability_tat',
            field=models.CharField(default='X', max_length=25),
        ),
        migrations.AddField(
            model_name='test_information',
            name='critical_values',
            field=models.CharField(default='X', max_length=25),
        ),
        migrations.AddField(
            model_name='test_information',
            name='eap',
            field=models.CharField(default='X', max_length=25),
        ),
        migrations.AddField(
            model_name='test_information',
            name='instrument',
            field=models.CharField(default='X', max_length=25),
        ),
        migrations.AddField(
            model_name='test_information',
            name='labs',
            field=models.CharField(default='X', max_length=25),
        ),
        migrations.AddField(
            model_name='test_information',
            name='methodology',
            field=models.CharField(default='X', max_length=25),
        ),
        migrations.AddField(
            model_name='test_information',
            name='outreach_notes',
            field=models.CharField(default='X', max_length=25),
        ),
        migrations.AddField(
            model_name='test_information',
            name='reference_range',
            field=models.CharField(default='X', max_length=25),
        ),
        migrations.AddField(
            model_name='test_information',
            name='reportable_range',
            field=models.CharField(default='X', max_length=25),
        ),
        migrations.AddField(
            model_name='test_information',
            name='source_of_reference_range',
            field=models.CharField(default='X', max_length=25),
        ),
        migrations.AddField(
            model_name='test_information',
            name='special_instructions',
            field=models.CharField(default='X', max_length=25),
        ),
        migrations.AddField(
            model_name='test_information',
            name='synonym',
            field=models.CharField(default='X', max_length=25),
        ),
        migrations.AddField(
            model_name='test_information',
            name='units',
            field=models.CharField(default='X', max_length=25),
        ),
    ]
