# Generated by Django 3.2.6 on 2021-10-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testinformation', '0006_auto_20211026_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_information',
            name='methodology',
            field=models.CharField(default='X', max_length=300),
        ),
    ]
