# Generated by Django 3.2.6 on 2021-10-26 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testinformation', '0009_test_information_tat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test_information',
            old_name='avaliability_tat',
            new_name='avaliability',
        ),
    ]
