# Generated by Django 3.2.6 on 2021-10-27 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testinformation', '0011_auto_20211027_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test_information',
            old_name='subdiscipine',
            new_name='subdiscipline',
        ),
    ]
