# Generated by Django 3.2.6 on 2021-11-05 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testinformation', '0012_rename_subdiscipine_test_information_subdiscipline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_information',
            name='appropriate_tubetype_three',
        ),
        migrations.RemoveField(
            model_name='test_information',
            name='appropriate_tubetype_two',
        ),
        migrations.RemoveField(
            model_name='test_information',
            name='frozen_stability',
        ),
    ]
